package Penjualan;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Administrator
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        masterMN = new javax.swing.JMenu();
        barangMN = new javax.swing.JMenuItem();
        userMN = new javax.swing.JMenuItem();
        transaksiMN = new javax.swing.JMenu();
        penjualanMN = new javax.swing.JMenuItem();
        laporanMN = new javax.swing.JMenu();
        formLaporanMN = new javax.swing.JMenuItem();
        logoutMN = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        masterMN.setText("Master");

        barangMN.setText("Barang");
        barangMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangMNActionPerformed(evt);
            }
        });
        masterMN.add(barangMN);

        userMN.setText("User");
        userMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userMNActionPerformed(evt);
            }
        });
        masterMN.add(userMN);

        jMenuBar1.add(masterMN);

        transaksiMN.setText("Transaksi");

        penjualanMN.setText("Penjualan");
        penjualanMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjualanMNActionPerformed(evt);
            }
        });
        transaksiMN.add(penjualanMN);

        jMenuBar1.add(transaksiMN);

        laporanMN.setText("Laporan");

        formLaporanMN.setText("Form Laporan");
        formLaporanMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formLaporanMNActionPerformed(evt);
            }
        });
        laporanMN.add(formLaporanMN);

        jMenuBar1.add(laporanMN);

        logoutMN.setText("Logout");
        logoutMN.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                logoutMNMenuSelected(evt);
            }
        });
        jMenuBar1.add(logoutMN);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barangMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangMNActionPerformed
        // TODO add your handling code here:
        FormBarang fBarang=new FormBarang(); 
        fBarang.setLocationRelativeTo(null); 
        fBarang.setVisible(true);
    }//GEN-LAST:event_barangMNActionPerformed

    private void userMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userMNActionPerformed
        // TODO add your handling code here:
        FormUser fUser=new FormUser(); 
        fUser.setLocationRelativeTo(null); 
        fUser.setVisible(true);
    }//GEN-LAST:event_userMNActionPerformed

    private void penjualanMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjualanMNActionPerformed
        // TODO add your handling code here:
        FormTransaksi fTransaksi=new FormTransaksi(); 
        fTransaksi.setLocationRelativeTo( null ); 
        fTransaksi.setVisible(true);
    }//GEN-LAST:event_penjualanMNActionPerformed

    private void formLaporanMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formLaporanMNActionPerformed
        // TODO add your handling code here:
        FormLaporan fLaporan=new FormLaporan();     
        fLaporan.setLocationRelativeTo( null ); 
        fLaporan.setVisible(true);
    }//GEN-LAST:event_formLaporanMNActionPerformed

    private void logoutMNMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_logoutMNMenuSelected
        // TODO add your handling code here:
        this.dispose() ; 
        FormLogIn fLogIn=new FormLogIn (); 
        fLogIn.setLocationRelativeTo(null); 
        fLogIn.setVisible(true);
    }//GEN-LAST:event_logoutMNMenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem barangMN;
    private javax.swing.JMenuItem formLaporanMN;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu laporanMN;
    private javax.swing.JMenu logoutMN;
    private javax.swing.JMenu masterMN;
    private javax.swing.JMenuItem penjualanMN;
    private javax.swing.JMenu transaksiMN;
    private javax.swing.JMenuItem userMN;
    // End of variables declaration//GEN-END:variables
}
